{
 "title": "VPC Flow Logs",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "VPC General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Min_Max_Avg Bytes",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "stats avg(bytes), min(bytes), max(bytes)",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "Min_Max_Avg_bar",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expression": "filter action=\"ACCEPT\" |\nstats avg(bytes), min(bytes), max(bytes)",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    },
    {
     "title": "Top 20 IP's with maximum rejects",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expression": "filter action=\"REJECT\"\n| stats count(*) as numRejections by srcAddr\n| sort numRejections desc\n| limit 20",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [ "srcAddr" ]
      }
     ]
    },
    {
     "title": "Top 20 IP's with least rejects",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expression": "filter action=\"REJECT\"\n| stats count(*) as numRejections by srcAddr\n| sort numRejections\n| limit 20",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [ "srcAddr" ]
      }
     ]
    },
    {
     "title": "Rejection trend",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expression": "filter action=\"REJECT\"\n| stats count(*) as numRejections by @timestamp\n| sort @timestamp desc",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [ "@timestamp" ]
      }
     ]
    },
    {
     "title": "Top 20 packet transfers",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "stats sum(packets) as packetsTransferred by srcAddr, dstAddr\n| sort packetsTransferred  desc\n| limit 20",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [
        "srcAddr",
        "dstAddr"
       ]
      }
     ]
    },
    {
     "title": "Top 10 byte transfers by source and destination IP addresses",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "stats sum(bytes) as bytesTransferred by srcAddr, dstAddr\n| sort bytesTransferred desc\n| limit 10",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [
        "srcAddr",
        "dstAddr"
       ]
      }
     ]
    },
    {
     "title": "Network Latency",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expression": "stats avg( end - start)/1000 as latency group by srcAddr, dstAddr\n| sort by latency desc\n| limit 10",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [
        "srcAddr",
        "dstAddr"
       ]
      }
     ]
    },
    {
     "title": "Top packet transfers",
     "type": "netsage-sankey-panel",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expression": "stats sum(packets) as packetsTransferred by srcAddr, dstAddr\n| limit 4",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [
        "srcAddr",
        "dstAddr"
       ]
      }
     ]
    },
    {
     "title": "Egress to Internet Bytes per AZ (For Nitro Systems)",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "filter flowDirection=\"egress\" and trafficPath=8\n| stats sum(bytes) by azId",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [ "azId" ]
      }
     ]
    },
    {
     "title": "Incoming HTTP Traffic per Instance",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expression": "filter dstPort=80 and not(isempty(instanceId))\n| stats sum(bytes) as BytesReceived by instanceId",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default",
       "statsGroups": [ "instanceId" ]
      }
     ]
    },
    {
     "title": "Ingress Traffic to DynamoDB",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "filter action=\"ACCEPT\" and pktDstAwsService=\"DYNAMODB\"\n| stats sum(bytes) as Received",
       "logGroupNames": [
        "vpc-flow-log-VPCFlowLogGroup-SKbQPvYd3mPN"
       ],
       "queryMode": "Logs",
       "region": "default"
      }
     ]
    }
   ]
  },
  { "title": "From Metric Expressions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Rejected Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "alias": "rejected-traffic",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sqlExpression": "SELECT AVG(\"Rejected-Traffic\") FROM SCHEMA(\"FlowLogs-Metrics\")",
     "statistic": "Average"
    }
   ]
  },
  { "title": "From Contributor Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Bytes Transferred",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "alias": "Average",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "INSIGHT_RULE_METRIC('Bytes-transferred', 'Average')",
     "statistic": "Average"
    },
    {
     "alias": "Miinimum",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "INSIGHT_RULE_METRIC('Bytes-transferred', 'Minimum')",
     "statistic": "Average"
    },
    {
     "alias": "Maximum",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "INSIGHT_RULE_METRIC('Bytes-transferred', 'Maximum')",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Traffic-by-source-address-and-action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "alias": "Average",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "INSIGHT_RULE_METRIC('Traffic-by-source-address-and-action', 'Average')",
     "statistic": "Average"
    },
    {
     "alias": "Miinimum",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "INSIGHT_RULE_METRIC('Traffic-by-source-address-and-action', 'Minimum')",
     "statistic": "Average"
    },
    {
     "alias": "Maximum",
     "metricEditorMode": 1,
     "metricQueryType": 1,
     "queryMode": "Metrics",
     "region": "default",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "sqlExpression": "INSIGHT_RULE_METRIC('Traffic-by-source-address-and-action', 'Maximum')",
     "statistic": "Average"
    }
   ]
  }
 ]
}